export interface ExifFieldInfo {
  label: string;
  description: string;
}

/** 面向非技术用户的常用元数据字段中文名与说明；同时是“常用信息”板块展示范围的唯一数据源。 */
const fieldInfo: Record<string, ExifFieldInfo> = {
  DateTimeOriginal: { label: '拍摄时间', description: '相机记录的画面拍摄日期和时间，精确到秒。对外分享前建议确认是否需要保留。' },
  CreateDate: { label: '创建时间', description: '元数据记录的文件创建时间，取自相机时钟，不一定等于实际拍摄时刻。' },
  Artist: { label: '作者', description: '拍摄者或作者署名，通常由相机或导入软件写入。' },
  Creator: { label: '创作者', description: 'XMP 标准里的创作者信息，可能与“作者”内容重复。' },
  Copyright: { label: '版权', description: '版权声明文字，例如“© 张三 2026”。' },
  Software: { label: '处理软件', description: '生成或编辑过这张图片的软件名称与版本，例如相机固件或修图工具。' },
  Make: { label: '相机品牌', description: '拍摄设备的制造商名称。' },
  Model: { label: '相机型号', description: '拍摄设备的具体型号。型号加上时间等信息可能帮助识别照片来源设备。' },
  CameraModelName: { label: '相机型号名称', description: '更完整的拍摄设备显示名称。' },
  LensModel: { label: '镜头型号', description: '拍摄所用镜头的型号标识，属于设备隐私信息。' },
  LensID: { label: '镜头编号', description: '镜头的数字编号标识，与镜头型号作用类似。' },
  LensInfo: { label: '镜头参数', description: '镜头焦段与最大光圈等参数组合。' },
  FocalLength: { label: '焦距', description: '拍摄时镜头的焦距（毫米），反映画面视野宽窄。' },
  FNumber: { label: '光圈值', description: 'F 值，表示拍摄时镜头的进光大小。' },
  Aperture: { label: '光圈', description: '光圈档位，与“光圈值”表达同一含义。' },
  ExposureTime: { label: '曝光时间', description: '快门开启的时长（秒），即常说的快门速度。' },
  ShutterSpeed: { label: '快门速度', description: '曝光时间的另一种记录方式。' },
  ISO: { label: '感光度', description: '传感器对光线的敏感程度，弱光环境下拍摄的数值通常较高。' },
  PhotographicSensitivity: { label: '感光参数', description: '标准化的感光度记录，通常与 ISO 数值相同。' },
  Flash: { label: '闪光灯', description: '拍摄时是否使用了闪光灯。' },
  Orientation: { label: '显示方向', description: '指示图片显示时是否需要旋转。删除后图片将按原始像素方向显示，可能导致画面横倒。' },
  DateTime: { label: '修改时间', description: 'EXIF 记录的图片最后修改时间，随保存操作更新。' },
  DateTimeDigitized: { label: '数字化时间', description: '照片被相机数字化保存的时间。' },
  SubsecTimeOriginal: { label: '拍摄毫秒', description: '拍摄时间的小数秒部分。' },
  OffsetTimeOriginal: { label: '拍摄时区', description: '拍摄时所处的时区偏移。' },
  ExposureProgram: { label: '曝光模式', description: '程序自动、光圈优先等相机测光档位。' },
  ExposureCompensation: { label: '曝光补偿', description: '拍摄时对自动曝光做出的明暗调整量。' },
  ApertureValue: { label: '光圈值（APEX）', description: '以 APEX 记法记录的光圈大小，与 F 值表达同一含义。' },
  MaxApertureValue: { label: '镜头最大光圈', description: '镜头在该焦距下能开到的最大光圈。' },
  BrightnessValue: { label: '场景亮度', description: '相机测得的被摄场景亮度。' },
  ExposureBiasValue: { label: '测光偏差', description: '测光系统记录的曝光偏差值。' },
  MeteringMode: { label: '测光模式', description: '评价测光、点测光等相机测光方式。' },
  LightSource: { label: '光源', description: '相机识别或设置的照明光源类型。' },
  WhiteBalance: { label: '白平衡', description: '拍摄时的白平衡设置，自动或手动。' },
  SceneCaptureType: { label: '场景模式', description: '相机选择的拍摄场景模式（标准、人像等）。' },
  SensitivityType: { label: '感光度类型', description: 'ISO 数值的测定方式说明。' },
  SensingMethod: { label: '感光元件', description: '相机传感器的曝光方式（如单色芯片、Bayer 阵列）。' },
  FileSource: { label: '文件来源', description: '图像的采集来源类型，如数码相机。' },
  SceneType: { label: '场景类别', description: '拍摄场景的一级类别标记。' },
  Contrast: { label: '对比度', description: '相机内处理的对比度强度设置。' },
  Saturation: { label: '饱和度', description: '相机内处理的色彩饱和度设置。' },
  Sharpness: { label: '锐度', description: '相机内处理的画面锐度设置。' },
  DigitalZoomRatio: { label: '数码变焦', description: '在光学变焦基础上追加的数码放大倍数。' },
  SubjectDistance: { label: '主体距离', description: '拍摄时估算的对焦主体距离。' },
  XResolution: { label: '横向分辨率', description: '图片每英寸像素数（横向），仅影响打印尺寸。' },
  YResolution: { label: '纵向分辨率', description: '图片每英寸像素数（纵向），仅影响打印尺寸。' },
  ResolutionUnit: { label: '分辨率单位', description: '分辨率数值采用的单位（英寸或厘米）。' },
  ImageDescription: { label: '图片描述', description: '写入元数据的图片文字说明。' },
  MakeNote: { label: '厂商备注', description: '相机厂商私有的拍摄参数记录。' },
  HostComputer: { label: '处理电脑', description: '最后保存该图片时所在的电脑名称，可能暴露设备信息。' },
  ColorSpace: { label: '色彩空间', description: '图片采用的色彩标准标识（sRGB、未标定等）。' },
  GPSVersionID: { label: 'GPS 版本', description: 'GPS 信息使用的格式版本号。' },
  GPSLatitude: { label: '拍摄纬度', description: '拍摄位置的纬度坐标，属于精确位置隐私，分享前建议删除。' },
  GPSLongitude: { label: '拍摄经度', description: '拍摄位置的经度坐标，属于精确位置隐私，分享前建议删除。' },
  GPSLatitudeRef: { label: '纬度半球', description: '纬度的南北半球标记。' },
  GPSLongitudeRef: { label: '经度半球', description: '经度的东西半球标记。' },
  GPSAltitude: { label: '拍摄海拔', description: '拍摄位置的海拔高度。' },
  GPSAltitudeRef: { label: '海拔基准', description: '海拔高度的参考基准面。' },
  GPSTimeStamp: { label: 'GPS 时间', description: '定位时刻的协调世界时（UTC）。' },
  GPSDateStamp: { label: 'GPS 日期', description: '定位发生的日期。' },
  GPSSatellites: { label: '卫星编号', description: '定位使用的卫星列表。' },
  GPSStatus: { label: '定位状态', description: 'GPS 定位是否有效的状态标记。' },
  GPSMeasureMode: { label: '定位模式', description: '二维或三维定位模式。' },
  GPSDOP: { label: '定位精度', description: '位置精度衰减因子，数值越小定位越准。' },
  GPSSpeed: { label: '拍摄速度', description: '拍摄瞬间的移动速度。' },
  GPSSpeedRef: { label: '速度单位', description: '移动速度采用的单位。' },
  GPSTrack: { label: '移动方向', description: '拍摄时移动的方向角。' },
  GPSTrackRef: { label: '方向基准', description: '移动方向采用的参照系。' },
  GPSImgDirection: { label: '镜头朝向', description: '镜头朝向的角度。' },
  GPSMapDatum: { label: '坐标基准', description: 'GPS 坐标使用的地理基准椭球（如 WGS-84）。' },
  GPSDifferential: { label: '差分校正', description: '是否使用差分基站校正定位。' },
  Title: { label: '标题', description: '为图片写的标题文字。' },
  Description: { label: '描述', description: '为图片写的说明文字。' },
  Keywords: { label: '关键词', description: '为图片打上的关键词标签列表，可能包含作者刻意备注的信息。' },
  Rating: { label: '评分', description: '图片的星级评分（0–5）。' },
  Label: { label: '颜色标签', description: '管理软件使用的颜色分类标记。' },
  Credit: { label: '来源署名', description: '图片的提供或来源方名称。' },
  Headline: { label: '主标题', description: '编辑用途的标题文字。' },
  Source: { label: '来源', description: '图片的原始出处。' },
  Instructions: { label: '修改说明', description: '给编辑或后续使用者的操作提示。' },
  UsageTerms: { label: '使用条款', description: '图片的授权或使用条款说明。' },
  ObjectName: { label: '对象名称', description: 'IPTC 记录的图片对象名称。' },
  CreatorTool: { label: '创作工具', description: '生成该文件所使用的软件。' },
  MetadataDate: { label: '元数据修改时间', description: '元数据最后一次被修改的时间。' },
  ModifyDate: { label: '修改时间', description: '元数据记录的文件修改时间。' },
};

export function fieldInfoFor(name: string): ExifFieldInfo | undefined {
  return fieldInfo[name];
}

export const commonFieldNames = new Set([
  'DateTimeOriginal', 'CreateDate', 'Artist', 'Creator', 'Copyright', 'Software',
  'Make', 'Model', 'CameraModelName', 'LensModel', 'LensID', 'LensInfo',
  'FocalLength', 'FNumber', 'Aperture', 'ExposureTime', 'ShutterSpeed',
  'ISO', 'PhotographicSensitivity', 'Flash', 'Orientation',
]);
